version: 0.2

phases:
  build:
    commands:
      - echo Build started on `date` from dir `pwd`
      - echo Release $Commit_ID
      - echo Branch $Branch_Name
      # Copy default .env template from S3, add current release and upload it back to be used by CodeDeploy action.
      - |-
        if [ "$Branch_Name" = "STAGING" ]; then
          s3_bucket="verofy-2-staging-private-env-files/verofy-2-knowledge-base-book-stack"
        elif [ "$Branch_Name" = "PRODUCTION_CUSTOMER" ]; then
          s3_bucket="verofy-2-production-private-env-files/verofy-2-knowledge-base-book-stack-customer"
        elif [ "$Branch_Name" = "PRODUCTION_PARTNER" ]; then
          s3_bucket="verofy-2-production-private-env-files/verofy-2-knowledge-base-book-stack-partner"
        elif [ "$Branch_Name" = "PRODUCTION_INTERNAL" ]; then
          s3_bucket="verofy-2-production-private-env-files/verofy-2-knowledge-base-book-stack-internal"
        fi
      - aws s3 cp s3://$s3_bucket/.env.default .env
      - sed -i "s/SENTRY_RELEASE=0/SENTRY_RELEASE=$Commit_ID/g" .env
      - aws s3 cp .env s3://$s3_bucket/.env
